packages:
  # Dashboard application
  - "apps/dashboard"

  # MCP Server packages
  - "packages/mcp-lead-discovery"
  - "packages/mcp-site-audit"
  - "packages/mcp-email-outreach"
  - "packages/mcp-lead-storage"
  - "packages/mcp-calendar"

  # Shared utilities
  - "packages/shared"
